global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'server1'
    static_configs:
      - targets: ['server1:your_exporter_port']  # Server 1 container and port

  - job_name: 'server2'
    static_configs:
      - targets: ['server2:your_exporter_port']  # Server 2 container and port

  - job_name: 'mongo-primary'
    static_configs:
      - targets: ['mongodb-primary:27017']  # MongoDB primary container and port

  - job_name: 'mongo-backup'
    static_configs:
      - targets: ['mongodb-backup:27018']  # MongoDB backup container and port

