{
 "title": "Megalodon",
 "description": "the big behemoth dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(nginx_connections_writing[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Generated",
   "type": "stat",
   "description": "Total number of transactions generated by each instance",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (transactions_generated_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) + rate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"nginx\"} |= `.0.5` [1m])"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"nginx\"} |= `.0.6` [1m])"
    }
   ]
  },
  {
   "title": "Total Transaction Errors",
   "type": "timeseries",
   "description": "Amount of failed transactions over time",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(transaction_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "mongodb_dbstats_totalSize{database=\"transactions_db\", instance=\"mongodb-exporter\", job=\"mongodb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 18 },
   "targets": [
    { "expr": "mongodb_sys_memory_Active_kb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate of Transaction Consumption",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(mongodb_top_total_count{database=\"transactions_db\", collection=\"transactions\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{cluster_role=\"mongod\", instance=\"mongodb-exporter\", job=\"mongodb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Transaction Latency",
   "type": "timeseries",
   "description": "1 minute rolling average of transaction latency",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(transaction_latency_seconds_sum[1m])) by(instance) / sum(rate(transaction_latency_seconds_count[1m])) by(instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}