{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoDB Up",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{cluster_role=\"mongod\", instance=\"mongodb-exporter\", job=\"mongodb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Aborted",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_transactions_totalAborted{rs_state=\"1\"}",
     "legendFormat": "RS1"
    },
    {
     "expr": "mongodb_ss_transactions_totalAborted{rs_state=\"2\"}",
     "legendFormat": "RS2"
    }
   ]
  },
  {
   "title": "Total Committed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_transactions_totalCommitted{rs_state=\"1\"}",
     "legendFormat": "RS1"
    },
    {
     "expr": "mongodb_ss_transactions_totalCommitted{rs_state=\"2\"}",
     "legendFormat": "RS2"
    }
   ]
  },
  {
   "title": "Rate of Transaction Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(mongodb_top_total_count{database=\"transactions_db\", collection=\"transactions\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "mongodb_collstats_latencyStats_transactions_latency",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "targets": [
    { "expr": "mongodb_sys_memory_Active_kb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "mongodb_dbstats_totalSize{database=\"transactions_db\", instance=\"mongodb-exporter\", job=\"mongodb\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}