version: '3.8'

services:
  # Load Generators
  transaction-generator-1:
    build: 
      context: ./transaction-generator
      dockerfile: Dockerfile
    environment:
      - LOAD_BALANCER_URL=http://nginx:80
      - GENERATION_RATE=10
    depends_on:
      - nginx
    networks:
      - frontend
    deploy:
      restart_policy:
        condition: on-failure

  transaction-generator-2:
    build: 
      context: ./transaction-generator
      dockerfile: Dockerfile
    environment:
      - LOAD_BALANCER_URL=http://nginx:80
      - GENERATION_RATE=10
    depends_on:
      - nginx
    networks:
      - frontend
    deploy:
      restart_policy:
        condition: on-failure

  # Load Balancer
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    depends_on:
      - app-server-1
      - app-server-2

  # Application Servers
  app-server-1:
    build:
      context: ./app-server
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092
      - SERVER_ID=1
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app-server-2:
    build:
      context: ./app-server
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092
      - SERVER_ID=2
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Kafka Cluster
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka_net
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
    networks:
      - kafka_net
      - backend
    volumes:
      - kafka1_data:/var/lib/kafka/data

  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
    networks:
      - kafka_net
      - backend
    volumes:
      - kafka2_data:/var/lib/kafka/data

  # MongoDB Replica Set
  mongo-1:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo1_data:/data/db
    networks:
      - db_net
    ports:
      - "27017:27017"

  mongo-2:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo2_data:/data/db
    networks:
      - db_net
    ports:
      - "27018:27017"

  # Monitoring Stack
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring

  mongodb-exporter:
    image: percona/mongodb_exporter:0.43.1
    command:
      - '--mongodb.uri=mongodb://mongo-1:27017'
    networks:
      - monitoring
      - db_net
    depends_on:
      - mongo-1

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    command:
      - '--kafka.server=kafka-1:9092'
      - '--kafka.server=kafka-2:9092'
    networks:
      - monitoring
      - kafka_net

networks:
  frontend:
  backend:
  kafka_net:
  db_net:
  monitoring:

volumes:
  zookeeper_data:
  kafka1_data:
  kafka2_data:
  mongo1_data:
  mongo2_data:
  prometheus_data:
  grafana_data: