auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules

analytics:
  reporting_enabled: false

compactor:
  shared_store: filesystem

chunk_store_config:
  max_look_back_period: 0

table_manager:
  retention_deletes_enabled: false
  retention_period: 0

# ✅ Removed `query_scheduler.enabled`
memberlist:
  join_members: []

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
  chunk_idle_period: 5m
  chunk_block_size: 262144
  chunk_retain_period: 30s
  max_transfer_retries: 0

querier:
  max_concurrent: 8

distributor:
  ring:
    kvstore:
      store: inmemory

query_range:
  split_queries_by_interval: 0
